<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="26141" started-at="2019-12-31T23:58:19 PST" finished-at="2019-12-31T23:58:45 PST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="26141" started-at="2019-12-31T23:58:19 PST" finished-at="2019-12-31T23:58:45 PST">
      <class name="xerorRunner.testRunnerXero">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:xerorRunner.testRunnerXero@1445d7f]" name="setUpClass" is-config="true" duration-ms="483" started-at="2019-12-31T23:58:19 PST" finished-at="2019-12-31T23:58:20 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:xerorRunner.testRunnerXero@1445d7f]" name="feature" duration-ms="25430" started-at="2019-12-31T23:58:20 PST" data-provider="features" finished-at="2019-12-31T23:58:45 PST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Automate testCase in xero]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[org.junit.ComparisonFailure: expected:<Xero | Dashboard | [elf]> but was:<Xero | Dashboard | [hcl]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: org.junit.ComparisonFailure: expected:<Xero | Dashboard | [elf]> but was:<Xero | Dashboard | [hcl]>
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at xerorRunner.testRunnerXero.feature(testRunnerXero.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.junit.ComparisonFailure: expected:<Xero | Dashboard | [elf]> but was:<Xero | Dashboard | [hcl]>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at stepDefinitionXero.xeroStepDefinition.validate_the_url(xeroStepDefinition.java:196)
at âœ½.When : validate the url "Xero | Dashboard | elf"(xero.feature:12)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:xerorRunner.testRunnerXero@1445d7f]" name="tearDownClass" is-config="true" duration-ms="34" started-at="2019-12-31T23:58:45 PST" finished-at="2019-12-31T23:58:45 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- xerorRunner.testRunnerXero -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
